### ISSUE TITLE
files.component.ts - error

### ISSUE THREAD

**Issue by rrubio** [kornatzky/backand-angularjs2#1]
Hi Guys,

Just trying to get this demo up and working, but getting the following 2 errors:

1. app/files/files.component.ts:26:35
    Property 'result' does not exist on type 'EventTarget'.

2. app/files/files.component.ts:35:30
    Property 'files' does not exist on type 'EventTarget'.
[default] Checking finished with 2 errors

**Comment by adamlaz** [comment]
I was seeing that error too-- 

once I updated the `angular-cli.json` and `app.component.ts` it was no longer throwing that error. 

## `angular-cli.json` fix
migrate angular-cli.json to newer syntax
```ts
 "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
```
## `app.component.ts` fix
add your backand infos
```ts
constructor(private router: Router, private backandService:BackandService){
		this.backandService.setAppName('your app name');
        this.backandService.setSignUpToken('your signup token');
        this.backandService.setAnonymousToken('your anonymousToken token');
	}

**Comment by kornatzky** [comment]
Please switch to our newer starter using a newer version of our SDK

https://github.com/kornatzky/angularjs2_backand_javascript
